#!/bin/bash

muteled="platform::mute"
micmuteled="platform::micmute"

volstep=5
brightstep=5

if [[ $# -lt 1 ]]; then
    >&2 echo "usage: $0 <syncleds|volinc|voldec|volmutetog|micmutetog|brightinc|brightdec|fanoff|faninc|fandec|fanmax>"
    exit 1
fi

syncleds () {
    if [[ $(pactl get-sink-mute @DEFAULT_SINK@) =~ yes ]]; then
        ledctl $muteled on
    else
        ledctl $muteled off
    fi

    if [[ $(pactl get-source-mute @DEFAULT_SOURCE@) =~ yes ]]; then
        ledctl $micmuteled on
    else
        ledctl $micmuteled off
    fi
}

if [ "$1" = "syncleds" ]; then
    syncleds
elif [ "$1" = "volinc" ]; then
    pactl set-sink-volume @DEFAULT_SINK@ +$volstep%
    #notify-send "[+5%]"
elif [ "$1" = "voldec" ]; then
    pactl set-sink-volume @DEFAULT_SINK@ -$volstep%
elif [ "$1" = "volmutetog" ]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    syncleds
elif [ "$1" = "micmutetog" ]; then
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
    syncleds
elif [ "$1" = "brightinc" ]; then
    brightnessctl +$brightstep
elif [ "$1" = "brightdec" ]; then
    brightnessctl -$brightstep
elif [ "$1" = "fanoff" ]; then
    fanctl 0
elif [ "$1" = "fanmax" ]; then
    fanctl full-speed
elif [ "$1" = "faninc" ]; then
    current=$(cat /proc/acpi/ibm/fan | grep ^level | awk '{print $2}')
    fanctl $((current < 7 ? current + 1 : 7))
elif [ "$1" = "fandec" ]; then
    current=$(cat /proc/acpi/ibm/fan | grep ^level | awk '{print $2}')
    fanctl $((current > 0 ? current - 1 : 0))
else
    >&2 echo "Illegal parameter"
fi

